# Generated by Django 4.0.1 on 2023-04-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracleapp', '0002_memcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('prod_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=40)),
                ('prod_lgu', models.CharField(max_length=4)),
                ('prod_buyer', models.CharField(max_length=6)),
                ('prod_cost', models.IntegerField(max_length=10)),
                ('prod_price', models.IntegerField(max_length=10)),
                ('prod_sale', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'prod',
                'managed': False,
            },
        ),
    ]
