# Generated by Django 4.0.1 on 2023-04-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracleapp', '0003_prod'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartMemProd',
            fields=[
                ('cart_no', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('cart_qty', models.IntegerField(max_length=8)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
    ]
